"""add_server_default_to_api_call_count

Revision ID: a84b5ac15aaa
Revises: 50e81b39d14b
Create Date: 2025-06-22 14:12:08.856795+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84b5ac15aaa'
down_revision: Union[str, Sequence[str], None] = '50e81b39d14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
