"""add_rate_limiting_columns_to_profiles

Revision ID: 43305bd3b887
Revises: 249d8773b803
Create Date: 2025-06-22 12:26:16.323300+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43305bd3b887'
down_revision: Union[str, Sequence[str], None] = '249d8773b803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add api_call_count column as nullable first, then set default values and make it NOT NULL
    op.add_column('profiles', sa.Column('api_call_count', sa.Integer(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE profiles SET api_call_count = 0 WHERE api_call_count IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('profiles', 'api_call_count', nullable=False)
    
    # Add the rate_limit_reset_at column (nullable is fine)
    op.add_column('profiles', sa.Column('rate_limit_reset_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'rate_limit_reset_at')
    op.drop_column('profiles', 'api_call_count')
    # ### end Alembic commands ###
